import { Fragment, useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Button, Typography, Select, Input } from "antd";
import CountSteps from "../../components/steps";
import styles from "./index.module.css";
import { useSelector } from "react-redux";
import img1 from "../../assests/1.png";
import img2 from "../../assests/2.jpg";
import img3 from "../../assests/3.png";
import Image from "next/image";
import Script from "next/script";

import Step1 from "./Step1";
import Step2 from "./Step2";
import Step3 from "./Step3";
import ChoosePlans from "../../components/plans/ChoosePlans";
import NoPincode from "../../components/plans/NoPincode";
import Head from "next/head";
import { dispatch } from "../../store";
import { planActions } from "../../store/slices/stepSlice";

const MButton = motion(Button);

const Create = () => {
  const current = useSelector((state) => state.plan.step);
  const isAuth = useSelector((state) => state.auth.isAuth);
  const plans = useSelector((state) => state.plan.plans);
  const [updatedPlans, setUpdatedPlans] = useState([]);
  const [breeds, setBreeds] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [success, setSuccess] = useState(false);
  const [isPincode, setIsPincode] = useState(false);
  const [plan, setPlan] = useState({});
  const [pet, setPet] = useState([]);

  useEffect(() => {
    loadBreeds();
  }, []);

  useEffect(() => {
    setUpdatedPlans(plans);
  }, [plans]);

  useEffect(() => {
    if (!plans.hasOwnProperty("user")) {
      const email = localStorage.getItem("usersEmail");
      const name = localStorage.getItem("usersName");
      const mob = localStorage.getItem("usersMobile");
      const add = localStorage.getItem("usersAdd");
      const pin = localStorage.getItem("usersPin");

      if (email && name && mob && add && pin) {
        dispatch(
          planActions.setPlans({
            dog: [],
            user: {
              name: name,
              email: email,
              address: add,
              mobile: mob,
              pincode: pin,
            },
          })
        );
      }
    }
  }, []);

  const loadBreeds = () => {
    fetch("https://app-pet-api-6jjd-fhyky08wd-nemantaj.vercel.app/get-breeds")
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        if (!data.success) {
          console.log(data);
        }

        setBreeds(data.payload);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const createPlan = (user) => {
    setLoading(true);
    console.log(plans);
    fetch("https://app-pet-api-6jjd-fhyky08wd-nemantaj.vercel.app/create-plan", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ ...updatedPlans, user: user }),
    })
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        if (!data.success) {
          setLoading(false);
          return setError(true);
        }

        setIsPincode(data.isPincode);
        if (data.plan) {
          setPlan(data.plan);
          setPet(data.dog);
        }
        dispatch(planActions.setStep(100));
        return setLoading(false);
      })
      .catch((err) => {
        setLoading(false);
        return setError(true);
      });
  };

  return (
    <Fragment>
      <Head>
        <title>Build a plan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://sdk.cashfree.com/js/ui/2.0.0/cashfree.sandbox.js"></script>
      </Head>
      <motion.div className={styles.stepDiv}>
        <CountSteps current={current} />
      </motion.div>
      {current <= 25 && <Step1 />}
      {current <= 50 && current >= 26 && <Step2 breeds={breeds} />}
      {current <= 75 && current >= 52 && (
        <Step3 createPlan={createPlan} loading={loading} />
      )}
      {current <= 100 && current >= 76 && isPincode && !loading && (
        <ChoosePlans plan={plan} pet={pet} loading={loading} />
      )}
      {current <= 100 && current >= 76 && !isPincode && !loading && (
        <NoPincode loading={loading} />
      )}
    </Fragment>
  );
};

export default Create;
