import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import { Button } from "antd";
import { PlusOutlined } from "@ant-design/icons";

export default function Home() {
  const isAuth = useSelector((state) => state.auth.isAuth);
  const router = useRouter();

  useEffect(() => {
    if (isAuth) {
      if (isAuth) {
        router.push("/home");
      }
    }
  }, [isAuth]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Link href="/create" legacyBehavior>
          <Button
            type="primary"
            style={{ backgroundColor: "#f2674b" }}
            icon={<PlusOutlined />}
            shape="round"
          >
            Create a plan
          </Button>
        </Link>
      </div>
    </div>
  );
}
